---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: servicemeshoperators-latest
spec:
  type: GitHub
  pathname: https://github.com/trevorbox/service-mesh-patterns.git
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: servicemeshoperators
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - servicemeshoperators
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: servicemeshoperators
  labels:
    app: servicemeshoperators
  annotations:
    apps.open-cluster-management.io/github-path: auth/helm/servicemeshoperators
    apps.open-cluster-management.io/github-branch: rhacm
spec:
  channel: {{ .Release.Namespace }}/servicemeshoperators-latest
  placement:
    placementRef:
      kind: PlacementRule
      name: dev-clusters

